# Generated by Django 3.1.3 on 2020-11-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=15, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('numero', models.PositiveIntegerField(help_text='Solo Incluir Numeros', verbose_name='Número de Telefono')),
            ],
            options={
                'verbose_name': 'Escuela',
                'verbose_name_plural': 'Escuelas',
                'db_table': 'escuela',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=15, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('numero', models.PositiveIntegerField(help_text='Solo Incluir Numeros', verbose_name='Número de Telefono')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_manual', models.PositiveIntegerField(help_text='Solo Incluir Números', unique=True, verbose_name='Codigo Manual')),
                ('codigo_barra', models.PositiveIntegerField(help_text='Solo Incluir Números', unique=True, verbose_name='Codigo Barra')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio Costo')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Precio Venta')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('existencia', models.PositiveIntegerField(default=0, verbose_name='Existencia')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.proveedor')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
    ]
