# Generated by Django 3.1.3 on 2020-11-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_informeporrango'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeporrango',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Total Ventas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='informeporrango',
            name='total_compras',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Total de Compras'),
        ),
    ]
