# Generated by Django 3.1.3 on 2020-11-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20201128_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InformePorRango',
        ),
    ]
