# Generated by Django 3.1.3 on 2020-11-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=150, verbose_name='Cliente')),
                ('nit', models.CharField(max_length=15, unique=True, verbose_name='NIT')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='VentaEscuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.escuela')),
            ],
            options={
                'verbose_name': 'Venta a Escuela',
                'verbose_name_plural': 'Ventas a Escuelas',
                'db_table': 'venta_escuela',
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaEscuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Sub Total')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
                ('venta_escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.ventaescuela')),
            ],
            options={
                'verbose_name': 'Detalle de Venta a Escuelas',
                'verbose_name_plural': 'Detalles de Ventas a Escuelas',
                'db_table': 'detalle_venta_escuela',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Sub Total')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'detalle_venta',
            },
        ),
    ]
