# Generated by Django 3.1.3 on 2020-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='nit',
            field=models.CharField(max_length=15, verbose_name='NIT'),
        ),
    ]
