# Generated by Django 3.1.3 on 2020-11-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informeporrango',
            name='diferencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total Ventas'),
        ),
    ]
