# Generated by Django 3.1.3 on 2020-11-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informes', '0002_informeporrango_diferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Inventario de Productos',
                'verbose_name_plural': 'Inventario de Productos',
                'db_table': 'inventario',
            },
        ),
    ]
