# Generated by Django 3.1.3 on 2020-11-27 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dev', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta')], default='Venta', max_length=6, verbose_name='Tipo Devolución')),
                ('motivo', models.TextField(verbose_name='Motivo')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=7, verbose_name='Total de Devolución')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devolucion',
            },
        ),
        migrations.CreateModel(
            name='DetalleDev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devoluciones.devolucion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devoluciones',
                'db_table': 'detalle_devolucion',
            },
        ),
    ]
