# Generated by Django 3.1.3 on 2020-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledev',
            name='sub_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Subtotal'),
        ),
    ]
