# Generated by Django 3.1.3 on 2020-11-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='subtotal',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='subtotal'),
        ),
    ]
