# Generated by Django 3.1.3 on 2020-11-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_detallecompra_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=7, verbose_name='Precio Compra'),
            preserve_default=False,
        ),
    ]
