# Generated by Django 3.1.3 on 2020-11-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20201127_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Subtotal'),
        ),
    ]
